version: '3.7'
services:
  postgresqldb:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./env/psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  mysqldb:
    image: mysql:8.0.31
    ports:
      - '3306:3306'
    volumes:
      - ./env/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  gate-simulator:
    build: ./gate-simulator
    ports:
      - '9999:9999'